### ISSUE TITLE
Payslips download doesn't work anymore

### ISSUE THREAD

**Issue by pinage404** [konnectors/lucca#137]
My payslip for april has been downloaded under the name `2019_04.pdf` but the content isn't a PDF, the content is :

```json
{
  "message": "No HTTP resource was found that matches the request URI 'http://MYCOMPANY.ilucca.net/pagga/download/DOCUMENT_ID'."
}
```

I manually downloaded the payslip from Lucca and the download URL was https://MYCOMPANY.ilucca.net/pagga/services/download/DOCUMENT_ID

I think the URL should be changed

https://github.com/konnectors/lucca/blob/b306a954dfe6b7715d5082477e77e4c583060a4c/src/index.js#L111

```diff
-    const url = companyInstanceUrl + '/pagga/download/' + payslip.id
+    const url = companyInstanceUrl + '/pagga/services/download/' + payslip.id
```

**Comment by sebdalink** [comment]
Hello,

I've fixed download URL and tagged a new release. Now we wait validation on Cozy side.

**Comment by LucsT** [comment]
Validation is done, and connector is available is the store.

**Comment by LucsT** [comment]
@sebdalink Did you remove some commit from the master tree ?

The connector may had issue with new libs this weekend (cozy-konnectors-libs 4.18.0)
Reverting to 4.17.1 will works.

Moreover, i have trace of problems with some 6 digit code in some execution.

What can we do in your opinions ? (we haven't a lucca account for testing purpose)

**Comment by sebdalink** [comment]
@LucsT , I've done a pull before my git push, so I don't think I've missed a commit from master tree.

About 6 digit code issue, it's on lucca side. They have implemented this feature who ask a code sent by email after download request. It can be disabled by the company service who administrate Lucca (HR service for me).

Have you any idea how we can send a friendly error in this case ? Can you send me some anonymized error logs to see how can fix that ?

**Comment by LucsT** [comment]
@sebdalink 
Ok, i found 2 lost commits after reading your message.
The 2 last commit in the tagged 1.2.1 are not merged in master : https://github.com/konnectors/lucca/commits/1.2.1

I will :
 1) merge into master these commits
 2) publish a 1.2.2 with cozy-konnector-libs 4.17.1, and the change about download url
 3) I notify you for testing.

we will see what the situation after that.

**Comment by LucsT** [comment]
Done.
A version 1.2.2 is available. Can anyone can confirm every file is ok ?
@sebdalink

**Comment by sebdalink** [comment]
@LucsT Everything seems ok now. I can retreive all my payslips on my Cozy drive but now I can't change destination folder anymore. Does this feature has been removed ?

**Comment by LucsT** [comment]
We removed the feature "change the destination folder" because we faced some issues with it. It will be back, but it has not been prioritised yet. 
You still can move the folder manually in Cozy Drive.

I closed this issue. Thank's
